// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_VI-h9Zi6799plxjYxNlT43xszto7mqA',
    appId: '1:549043007746:web:4e302b65f69acaed70921b',
    messagingSenderId: '549043007746',
    projectId: 'junopay',
    authDomain: 'junopay.firebaseapp.com',
    storageBucket: 'junopay.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0A2zaLYnL2z_rBd_99X63WtOkD2MGEoI',
    appId: '1:549043007746:android:34da85f6cfb3324270921b',
    messagingSenderId: '549043007746',
    projectId: 'junopay',
    storageBucket: 'junopay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACGT0LuBN5DeNn67Dinrk6UzcLjsmvF0w',
    appId: '1:549043007746:ios:7b461a979172288f70921b',
    messagingSenderId: '549043007746',
    projectId: 'junopay',
    storageBucket: 'junopay.appspot.com',
    iosClientId: '549043007746-3r57g7i3rmpl7kahas9naqpnf7it4amp.apps.googleusercontent.com',
    iosBundleId: 'com.example.junoPai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACGT0LuBN5DeNn67Dinrk6UzcLjsmvF0w',
    appId: '1:549043007746:ios:f19b7880c05c834e70921b',
    messagingSenderId: '549043007746',
    projectId: 'junopay',
    storageBucket: 'junopay.appspot.com',
    iosClientId: '549043007746-5qtrc435o67l9jh3bmbrnc92vb652aq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.junoPai.RunnerTests',
  );
}
